name: thegreen_house
description: Build Social Network GreenHouse




version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"




dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^3.1.2
  cupertino_icons: ^1.0.0
  eva_icons_flutter: ^3.0.2
  firebase_auth: ^3.3.0
  firebase_core: ^1.10.2
  firebase_storage: ^10.2.0
  google_sign_in: ^5.2.1
  image_picker: ^0.8.4+4
  font_awesome_flutter: ^9.2.0
  page_transition: ^2.0.4
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
flutter_icons:
  image_path:"assets/images/logo.png"
android: true


flutter:
  uses-material-design: true
  assets:
    - assets/images/login.png
    - assets/images/greenhouse.png
    - assets/images/logo.png
  fonts:
    - family: Poppins
      fonts:
         - asset: assets/fonts/Poppins.ttf

    - family: Monteserrat
      fonts:
         - asset: assets/fonts/Monteserat.ttf




